version: "3"
services:
    app:
        container_name: "app"
        build:
            ./app
        volumes:
            - ./app:/app
            - /app/node_modules
        ports:
            - "3000:3000"
    api:
        container_name: "api"
        build:
            ./api/docker/api
            #./api
        volumes:
            - ./api:/var/www
    nginx:
        container_name: "nginx"
        build: ./api/docker/nginx
        restart: always
        ports:
            - "9001:80"
        volumes:
            - ./api:/var/www
        depends_on:
            - api
    mysql:
        container_name: "mysql"
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./api/docker/dbdata:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: api
            MYSQL_ROOT_PASSWORD: root