name: Laravel CI

on:
  push:
    branches: [ master ]

jobs:
  laravel-tests:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
       mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3  

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        cd api
        composer install
    - name: Generate key
      run: |
        cd api
        php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 api/storage api/bootstrap/cache
    - name: Create Database
      run: |
        cd api
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: |
        cd api
        vendor/bin/phpunit
